services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3001:80"

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - ./.backend:/data
